from models.user import User
from models.student import Student
from models.company import Company
from models.department import Department
from models.branch import Branch
from models.placement_drive import PlacementDrive
from models.skill import Skill
from models.interview import Interview
from models.application import Application
from models.placement import Placement