"""Remove application unique constraint

Revision ID: 7e9cf2d85e53
Revises: 
Create Date: 2026-07-13 23:26:30.174473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9cf2d85e53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_application_per_student_per_drive'), type_='unique')

    with op.batch_alter_table('placement_drive', schema=None) as batch_op:
        batch_op.alter_column('drive_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_drive', schema=None) as batch_op:
        batch_op.alter_column('drive_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_application_per_student_per_drive'), ['register_no', 'drive_id'])

    # ### end Alembic commands ###
